package com.healthcard.backend.entity.enums;

public enum AuditAction {
    LOGIN,
    PATIENT_RECORD_ACCESSED,
    PATIENT_RECORD_ACCESS_DENIED,
    PRESCRIPTION_CREATED,
    LAB_REPORT_UPLOADED,
    LAB_REPORT_VIEWED,
    APPOINTMENT_BOOKED,
    APPOINTMENT_STATUS_CHANGED,
    BILL_CREATED,
    BILL_PAID,
    DOCTOR_VERIFIED,
    PATHOLOGIST_VERIFIED,
    DOCTOR_AUTHORIZED_BY_PATIENT,
    DOCTOR_AUTHORIZATION_REVOKED
}
